// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiXFsJsUseIuFmbpSNQqfwas6TB51GBGo',
    appId: '1:221066763797:web:3160a41880c45fe9ab381c',
    messagingSenderId: '221066763797',
    projectId: 'irritant-tracker',
    authDomain: 'irritant-tracker.firebaseapp.com',
    storageBucket: 'irritant-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk_1agIclYRvLVu3aOjR0dZmHWKRvHj0Q',
    appId: '1:221066763797:android:aa2168f125193dcdab381c',
    messagingSenderId: '221066763797',
    projectId: 'irritant-tracker',
    storageBucket: 'irritant-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJJygOQyCPaKHWcxMQRppsIX3gfHdo3os',
    appId: '1:221066763797:ios:d1dddb276f15bdddab381c',
    messagingSenderId: '221066763797',
    projectId: 'irritant-tracker',
    storageBucket: 'irritant-tracker.firebasestorage.app',
    iosBundleId: 'com.example.irritantTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJJygOQyCPaKHWcxMQRppsIX3gfHdo3os',
    appId: '1:221066763797:ios:d1dddb276f15bdddab381c',
    messagingSenderId: '221066763797',
    projectId: 'irritant-tracker',
    storageBucket: 'irritant-tracker.firebasestorage.app',
    iosBundleId: 'com.example.irritantTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiXFsJsUseIuFmbpSNQqfwas6TB51GBGo',
    appId: '1:221066763797:web:6255e1b7c3b7bda1ab381c',
    messagingSenderId: '221066763797',
    projectId: 'irritant-tracker',
    authDomain: 'irritant-tracker.firebaseapp.com',
    storageBucket: 'irritant-tracker.firebasestorage.app',
  );
}
